name: Sync Files
on:
  push:
    branches:
      - component/1.8-somename
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          env
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          BRANCH_PREFIX: ${{ github.ref_name}}_${ Date.now().toString() }